project_id = "wchaptnajxqvfidwmccl"

[functions.send-contact]
verify_jwt = false

[functions.robotspeed-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.deliver-ebook]
verify_jwt = false
